// AP Physics 1 (algebra-based) equation sheet as an interactive solver + notes program.
// Conventions: G holds g = 9.8 m/s^2 (adjustable in Settings). Angles in degrees where noted.
// Expressions use explicit `*`, `~` for negation, `^^2` for squares, `|E` for powers of ten.
import type { Equation, Subject, Variable } from '../types';

const v = (sym: string, name: string): Variable => ({ sym, name });
const GRAV = '6.67|E~11';

function eq(
  id: string,
  menu: string,
  display: string,
  vars: Variable[],
  solve: Record<string, string>,
  notes: string[],
  mode?: 'deg' | 'rad',
): Equation {
  return { id, menu, display, vars, solve, notes, mode };
}

export const physics1: Subject = {
  program: 'PHYSICS1',
  title: 'AP PHYSICS 1',
  description:
    'Every equation from the AP Physics 1 equation sheet, organised by unit. Pick a formula, choose the unknown, type the knowns, get the answer. Each formula also has notes on when to use it.',
  constants: [{ sym: 'G', name: 'g (m/s2)', value: '9.8' }],
  intro: [
    'AP PHYSICS 1 SOLVER',
    'Pick a unit, then a formula. SOLVE asks for the knowns and computes the unknown. NOTES explains the formula.',
    'g = 9.8 m/s2 is preset. Change it under Settings. Angles are in degrees.',
  ],
  topics: [
    {
      id: 'kin',
      menu: 'Kinematics',
      notes: [
        'Use the constant-acceleration equations only when a is constant.',
        'Choose + direction first. Falling: a = -g if up is +.',
        'Pick the equation that has your 3 knowns and 1 unknown.',
        'v=v0+at (no x), x=x0+v0t+.5at2 (no v), v2=v02+2a dx (no t).',
      ],
      equations: [
        eq('v1', 'v=v0+at', 'v = v0 + a t', [v('V', 'v (m/s)'), v('U', 'v0 (m/s)'), v('A', 'a (m/s2)'), v('T', 't (s)')],
          { V: 'U+A*T', U: 'V-A*T', A: '(V-U)/T', T: '(V-U)/A' },
          ['Final velocity after time t with constant acceleration a.', 'v0 is the initial velocity. Signs matter: use negative a for slowing down.']),
        eq('x1', 'x=x0+v0t+at2/2', 'x = x0 + v0 t + .5 a t2', [v('X', 'x (m)'), v('P', 'x0 (m)'), v('U', 'v0 (m/s)'), v('A', 'a (m/s2)'), v('T', 't (s)')],
          { X: 'P+U*T+.5*A*T^^2', P: 'X-U*T-.5*A*T^^2', U: '(X-P-.5*A*T^^2)/T', A: '2*(X-P-U*T)/T^^2', T: 'solve(P+U*T+.5*A*T^^2-X,T,1)' },
          ['Position at time t. x0 is the starting position.', 'Solving for t is quadratic: the calculator returns the root nearest t=1. If it looks wrong, the other root may apply.']),
        eq('v2', 'v2=v02+2a dx', 'v2 = v02 + 2 a dx', [v('V', 'v (m/s)'), v('U', 'v0 (m/s)'), v('A', 'a (m/s2)'), v('D', 'dx (m)')],
          { V: 'sqrt(U^^2+2*A*D)', U: 'sqrt(V^^2-2*A*D)', A: '(V^^2-U^^2)/(2*D)', D: '(V^^2-U^^2)/(2*A)' },
          ['Relates speeds and displacement when time is unknown.', 'v and v0 come out positive (speeds); decide the direction yourself.']),
        eq('vavg', 'v avg=dx/dt', 'v avg = dx / dt', [v('V', 'v avg (m/s)'), v('D', 'dx (m)'), v('T', 'dt (s)')],
          { V: 'D/T', D: 'V*T', T: 'D/V' },
          ['Average velocity is displacement over elapsed time.', 'Average speed uses total distance instead of displacement.']),
        eq('aavg', 'a avg=dv/dt', 'a avg = dv / dt', [v('A', 'a (m/s2)'), v('D', 'dv (m/s)'), v('T', 'dt (s)')],
          { A: 'D/T', D: 'A*T', T: 'D/A' },
          ['Average acceleration is change in velocity over time.', 'dv = v final - v initial, so it can be negative.']),
        eq('fallv', 'Fall speed v', 'fall: v = sqrt(2 g h)', [v('V', 'v (m/s)'), v('H', 'h (m)')],
          { V: 'sqrt(2*G*H)', H: 'V^^2/(2*G)' },
          ['Speed after falling from rest through height h, no air resistance.', 'Same result as energy conservation: mgh = .5mv2.']),
        eq('fallt', 'Fall time t', 'fall: t = sqrt(2 h / g)', [v('T', 't (s)'), v('H', 'h (m)')],
          { T: 'sqrt(2*H/G)', H: '.5*G*T^^2' },
          ['Time to fall from rest through height h.', 'From h = .5 g t2.']),
        eq('range', 'Range R', 'R = v02 sin(2 theta)/g', [v('R', 'R (m)'), v('V', 'v0 (m/s)'), v('Q', 'angle (deg)')],
          { R: 'V^^2*sin(2*Q)/G', V: 'sqrt(R*G/sin(2*Q))', Q: '.5*sin^-1(R*G/V^^2)' },
          ['Horizontal range of a projectile launched and landing at the same height.', 'Max range at 45 degrees. Angles theta and 90-theta give the same range. Solving for the angle returns the smaller one.'], 'deg'),
        eq('hmax', 'Max height H', 'H = (v0 sin theta)2/(2g)', [v('H', 'H (m)'), v('V', 'v0 (m/s)'), v('Q', 'angle (deg)')],
          { H: '(V*sin(Q))^^2/(2*G)', V: 'sqrt(2*G*H)/sin(Q)', Q: 'sin^-1(sqrt(2*G*H)/V)' },
          ['Maximum height above the launch point.', 'At the top the vertical velocity is zero; horizontal velocity is unchanged.'], 'deg'),
        eq('tflight', 'Flight time T', 'T = 2 v0 sin(theta)/g', [v('T', 'T (s)'), v('V', 'v0 (m/s)'), v('Q', 'angle (deg)')],
          { T: '2*V*sin(Q)/G', V: 'G*T/(2*sin(Q))', Q: 'sin^-1(G*T/(2*V))' },
          ['Total time in the air when landing at launch height.', 'Time to the top is half of this.'], 'deg'),
        {
          id: 'comp', menu: 'Components', display: 'vx = v cos, vy = v sin',
          vars: [v('V', 'v (m/s)'), v('Q', 'angle (deg)')], mode: 'deg',
          compute: { inputs: ['V', 'Q'], outputs: [{ sym: 'X', name: 'vx (m/s)', expr: 'V*cos(Q)' }, { sym: 'Y', name: 'vy (m/s)', expr: 'V*sin(Q)' }] },
          notes: ['Split a vector into horizontal and vertical parts.', 'Angle measured from the horizontal (x axis).'],
        },
        {
          id: 'vec', menu: 'Vector v,angle', display: 'v = sqrt(vx2+vy2)',
          vars: [v('X', 'vx (m/s)'), v('Y', 'vy (m/s)')], mode: 'deg',
          compute: { inputs: ['X', 'Y'], outputs: [{ sym: 'V', name: 'v (m/s)', expr: 'sqrt(X^^2+Y^^2)' }, { sym: 'Q', name: 'angle (deg)', expr: 'tan^-1(Y/X)' }] },
          notes: ['Combine components into magnitude and direction.', 'tan^-1 gives -90 to 90 degrees: add 180 if vx is negative.'],
        },
      ],
    },
    {
      id: 'dyn',
      menu: 'Dynamics',
      notes: [
        'Draw a free-body diagram first. Sum forces along each axis: sum F = m a.',
        'Weight = mg acts down. Normal force is perpendicular to the surface.',
        'Static friction <= mu_s N (adjusts). Kinetic friction = mu_k N.',
        'Circular motion: net force toward center = m v2 / r.',
      ],
      equations: [
        eq('fma', 'F=ma', 'sum F = m a', [v('F', 'F net (N)'), v('M', 'm (kg)'), v('A', 'a (m/s2)')],
          { F: 'M*A', M: 'F/A', A: 'F/M' },
          ["Newton's 2nd law. F is the NET force along one axis.", 'If a = 0 the forces balance (equilibrium).']),
        eq('weight', 'Weight Fg=mg', 'Fg = m g', [v('W', 'Fg (N)'), v('M', 'm (kg)')],
          { W: 'M*G', M: 'W/G' },
          ['Gravitational force on a mass near the surface.', 'Mass in kg, weight in newtons.']),
        eq('fric', 'Friction f=muN', 'Ff = mu N', [v('F', 'Ff (N)'), v('U', 'mu'), v('N', 'N (N)')],
          { F: 'U*N', U: 'F/N', N: 'F/U' },
          ['Kinetic friction, or maximum static friction.', 'On a flat surface with no other vertical forces N = mg.']),
        eq('spring', 'Spring F=kx', 'Fs = k x', [v('F', 'Fs (N)'), v('K', 'k (N/m)'), v('X', 'x (m)')],
          { F: 'K*X', K: 'F/X', X: 'F/K' },
          ["Hooke's law. x is the stretch or compression from natural length.", 'The force points back toward equilibrium (restoring).']),
        eq('grav', 'F=Gm1m2/r2', 'F = G m1 m2 / r2', [v('F', 'F (N)'), v('M', 'm1 (kg)'), v('N', 'm2 (kg)'), v('R', 'r (m)')],
          { F: `${GRAV}*M*N/R^^2`, M: `F*R^^2/(${GRAV}*N)`, N: `F*R^^2/(${GRAV}*M)`, R: `sqrt(${GRAV}*M*N/F)` },
          ["Newton's law of gravitation. G = 6.67E-11 N m2/kg2.", 'r is center-to-center distance. Attractive, along the line joining the masses.']),
        eq('gsurf', 'g=GM/r2', 'g = G M / r2', [v('A', 'g (m/s2)'), v('M', 'M (kg)'), v('R', 'r (m)')],
          { A: `${GRAV}*M/R^^2`, M: `A*R^^2/${GRAV}`, R: `sqrt(${GRAV}*M/A)` },
          ['Gravitational field (free-fall acceleration) at distance r from a mass M.', 'Earth: M = 5.97E24 kg, r = 6.37E6 m gives 9.8.']),
        eq('ac', 'ac=v2/r', 'ac = v2 / r', [v('A', 'ac (m/s2)'), v('V', 'v (m/s)'), v('R', 'r (m)')],
          { A: 'V^^2/R', V: 'sqrt(A*R)', R: 'V^^2/A' },
          ['Centripetal acceleration points toward the center of the circle.', 'Speed constant, direction changing.']),
        eq('fc', 'Fc=mv2/r', 'Fc = m v2 / r', [v('F', 'Fc (N)'), v('M', 'm (kg)'), v('V', 'v (m/s)'), v('R', 'r (m)')],
          { F: 'M*V^^2/R', M: 'F*R/V^^2', V: 'sqrt(F*R/M)', R: 'M*V^^2/F' },
          ['Net inward force needed for circular motion at speed v.', 'Provided by tension, gravity, friction, normal force...']),
        eq('period', 'T=2 pi r/v', 'T = 2 pi r / v', [v('T', 'T (s)'), v('R', 'r (m)'), v('V', 'v (m/s)')],
          { T: '2*pi*R/V', R: 'V*T/(2*pi)', V: '2*pi*R/T' },
          ['Period of uniform circular motion: time for one lap.', 'Frequency f = 1/T.']),
        {
          id: 'incline', menu: 'Incline forces', display: 'N = mg cos, F = mg sin',
          vars: [v('M', 'm (kg)'), v('Q', 'angle (deg)')], mode: 'deg',
          compute: { inputs: ['M', 'Q'], outputs: [{ sym: 'N', name: 'N (N)', expr: 'M*G*cos(Q)' }, { sym: 'F', name: 'F along (N)', expr: 'M*G*sin(Q)' }, { sym: 'A', name: 'a no fric', expr: 'G*sin(Q)' }] },
          notes: ['Frictionless incline at angle theta above horizontal.', 'Normal force mg cos(theta); component of weight along the slope mg sin(theta).'],
        },
        {
          id: 'inclinef', menu: 'Incline a,fric', display: 'a = g(sin - mu cos)',
          vars: [v('Q', 'angle (deg)'), v('U', 'mu k')], mode: 'deg',
          compute: { inputs: ['Q', 'U'], outputs: [{ sym: 'A', name: 'a (m/s2)', expr: 'G*(sin(Q)-U*cos(Q))' }] },
          notes: ['Acceleration down a rough incline with kinetic friction.', 'If the result is negative the block will not slide (static case).'],
        },
        {
          id: 'atwood', menu: 'Atwood machine', display: 'a=(m2-m1)g/(m1+m2)',
          vars: [v('M', 'm1 (kg)'), v('N', 'm2 (kg)')],
          compute: { inputs: ['M', 'N'], outputs: [{ sym: 'A', name: 'a (m/s2)', expr: '(N-M)*G/(M+N)' }, { sym: 'T', name: 'Tension (N)', expr: '2*M*N*G/(M+N)' }] },
          notes: ['Two masses on a string over a frictionless, massless pulley.', 'Heavier side (m2) accelerates down. Tension is the same on both sides.'],
        },
      ],
    },
    {
      id: 'energy',
      menu: 'Energy',
      notes: [
        'Energy is conserved: Ki + Ui + W other = Kf + Uf.',
        'Work by friction removes mechanical energy (turns into heat).',
        'Choose a reference height where U = 0.',
        'Power is the rate of doing work: 1 W = 1 J/s.',
      ],
      equations: [
        eq('ke', 'KE=.5mv2', 'KE = .5 m v2', [v('K', 'KE (J)'), v('M', 'm (kg)'), v('V', 'v (m/s)')],
          { K: '.5*M*V^^2', M: '2*K/V^^2', V: 'sqrt(2*K/M)' },
          ['Kinetic energy of a moving object. Always positive.', 'Doubling speed quadruples KE.']),
        eq('peg', 'PEg=mgh', 'PEg = m g h', [v('P', 'PE (J)'), v('M', 'm (kg)'), v('H', 'h (m)')],
          { P: 'M*G*H', M: 'P/(G*H)', H: 'P/(M*G)' },
          ['Gravitational potential energy relative to a chosen zero height.', 'Only changes in height matter.']),
        eq('pes', 'PEs=.5kx2', 'PEs = .5 k x2', [v('P', 'PE (J)'), v('K', 'k (N/m)'), v('X', 'x (m)')],
          { P: '.5*K*X^^2', K: '2*P/X^^2', X: 'sqrt(2*P/K)' },
          ['Elastic potential energy stored in a spring stretched or compressed by x.']),
        eq('work', 'W=Fd cos', 'W = F d cos(theta)', [v('W', 'W (J)'), v('F', 'F (N)'), v('D', 'd (m)'), v('Q', 'angle (deg)')],
          { W: 'F*D*cos(Q)', F: 'W/(D*cos(Q))', D: 'W/(F*cos(Q))', Q: 'cos^-1(W/(F*D))' },
          ['Work done by a constant force. theta is the angle between force and displacement.', 'Force perpendicular to motion does no work. Friction does negative work (theta = 180).'], 'deg'),
        eq('power', 'P=W/t', 'P = W / t', [v('P', 'P (W)'), v('W', 'W (J)'), v('T', 't (s)')],
          { P: 'W/T', W: 'P*T', T: 'W/P' },
          ['Average power: energy transferred per second.']),
        eq('powerfv', 'P=Fv', 'P = F v', [v('P', 'P (W)'), v('F', 'F (N)'), v('V', 'v (m/s)')],
          { P: 'F*V', F: 'P/V', V: 'P/F' },
          ['Instantaneous power when force and velocity are parallel.']),
        eq('wet', 'W=dKE', 'W = .5 m (v2 - v02)', [v('W', 'W net (J)'), v('M', 'm (kg)'), v('V', 'v (m/s)'), v('U', 'v0 (m/s)')],
          { W: '.5*M*(V^^2-U^^2)', M: '2*W/(V^^2-U^^2)', V: 'sqrt(2*W/M+U^^2)', U: 'sqrt(V^^2-2*W/M)' },
          ['Work-energy theorem: net work equals the change in kinetic energy.']),
        eq('cons', 'Energy consv', 'v2=v02+2g(h0-h)', [v('V', 'v (m/s)'), v('U', 'v0 (m/s)'), v('H', 'h0 (m)'), v('L', 'h (m)')],
          { V: 'sqrt(U^^2+2*G*(H-L))', U: 'sqrt(V^^2-2*G*(H-L))', H: 'L+(V^^2-U^^2)/(2*G)', L: 'H-(V^^2-U^^2)/(2*G)' },
          ['Mechanical energy conservation with no friction: .5mv02 + mgh0 = .5mv2 + mgh.', 'Mass cancels. Works for any path (ramps, loops, pendulums).']),
        eq('launch', 'Spring launch', 'v = x sqrt(k/m)', [v('V', 'v (m/s)'), v('X', 'x (m)'), v('K', 'k (N/m)'), v('M', 'm (kg)')],
          { V: 'X*sqrt(K/M)', X: 'V*sqrt(M/K)', K: 'M*V^^2/X^^2', M: 'K*X^^2/V^^2' },
          ['Speed of a mass launched horizontally by a spring compressed by x.', 'From .5kx2 = .5mv2.']),
      ],
    },
    {
      id: 'mom',
      menu: 'Momentum',
      notes: [
        'Momentum p = mv is a vector: keep track of signs.',
        'In any collision or explosion total momentum is conserved.',
        'Elastic: KE also conserved. Inelastic: KE lost. Perfectly inelastic: objects stick.',
        'Impulse J = F dt = change in momentum.',
      ],
      equations: [
        eq('p', 'p=mv', 'p = m v', [v('P', 'p (kg m/s)'), v('M', 'm (kg)'), v('V', 'v (m/s)')],
          { P: 'M*V', M: 'P/V', V: 'P/M' },
          ['Linear momentum. Same direction as velocity.']),
        eq('imp', 'J=F dt', 'J = F dt', [v('J', 'J (N s)'), v('F', 'F avg (N)'), v('T', 'dt (s)')],
          { J: 'F*T', F: 'J/T', T: 'J/F' },
          ['Impulse delivered by an average force over a time interval.', 'Equals the area under a force-time graph.']),
        eq('impmom', 'F dt=m dv', 'F dt = m (v - v0)', [v('F', 'F avg (N)'), v('T', 'dt (s)'), v('M', 'm (kg)'), v('V', 'v (m/s)'), v('U', 'v0 (m/s)')],
          { F: 'M*(V-U)/T', T: 'M*(V-U)/F', M: 'F*T/(V-U)', V: 'U+F*T/M', U: 'V-F*T/M' },
          ['Impulse-momentum theorem. Longer contact time means smaller force for the same change.']),
        eq('inel', 'Stick together', "v'=(m1v1+m2v2)/(m1+m2)", [v('M', 'm1 (kg)'), v('V', 'v1 (m/s)'), v('N', 'm2 (kg)'), v('W', 'v2 (m/s)'), v('F', "v' (m/s)")],
          { F: '(M*V+N*W)/(M+N)', V: '(F*(M+N)-N*W)/M', W: '(F*(M+N)-M*V)/N', M: 'N*(W-F)/(F-V)', N: 'M*(V-F)/(F-W)' },
          ['Perfectly inelastic collision: the objects move together afterwards.', 'Use negative velocity for objects moving the other way.']),
        {
          id: 'elastic', menu: 'Elastic 1D', display: 'elastic collision 1D',
          vars: [v('M', 'm1 (kg)'), v('V', 'v1 (m/s)'), v('N', 'm2 (kg)'), v('W', 'v2 (m/s)')],
          compute: { inputs: ['M', 'V', 'N', 'W'], outputs: [{ sym: 'X', name: "v1' (m/s)", expr: '((M-N)*V+2*N*W)/(M+N)' }, { sym: 'Y', name: "v2' (m/s)", expr: '(2*M*V+(N-M)*W)/(M+N)' }] },
          notes: ['Head-on elastic collision: both momentum and kinetic energy conserved.', 'Equal masses simply swap velocities.'],
        },
        eq('recoil', 'Recoil/explode', 'm1 v1 = -m2 v2', [v('M', 'm1 (kg)'), v('V', 'v1 (m/s)'), v('N', 'm2 (kg)'), v('W', 'v2 (m/s)')],
          { V: '~N*W/M', W: '~M*V/N', M: '~N*W/V', N: '~M*V/W' },
          ['Two objects pushed apart from rest: equal and opposite momenta.', 'Result comes out negative: the other object moves the opposite way.']),
        eq('cm', 'Center of mass', 'xcm=(m1x1+m2x2)/(m1+m2)', [v('X', 'xcm (m)'), v('M', 'm1 (kg)'), v('A', 'x1 (m)'), v('N', 'm2 (kg)'), v('B', 'x2 (m)')],
          { X: '(M*A+N*B)/(M+N)', A: '(X*(M+N)-N*B)/M', B: '(X*(M+N)-M*A)/N' },
          ['Position of the center of mass of two objects on a line.', 'The center of mass moves as if all external forces act there.']),
      ],
    },
    {
      id: 'rot',
      menu: 'Rotation',
      notes: [
        'Rotational quantities mirror linear ones: theta-x, omega-v, alpha-a, I-m, torque-F, L-p.',
        'Torque = r F sin(theta), largest when the force is perpendicular to the lever arm.',
        'Angular momentum is conserved when net external torque is zero.',
        'I = c m r2 with c: hoop 1, disk 1/2, solid sphere 2/5, shell 2/3, rod center 1/12, rod end 1/3.',
      ],
      equations: [
        eq('w1', 'w=w0+at', 'w = w0 + alpha t', [v('W', 'w (rad/s)'), v('U', 'w0 (rad/s)'), v('A', 'alpha rad/s2'), v('T', 't (s)')],
          { W: 'U+A*T', U: 'W-A*T', A: '(W-U)/T', T: '(W-U)/A' },
          ['Angular velocity with constant angular acceleration.']),
        eq('th1', 'th=w0t+at2/2', 'theta = w0 t + .5 alpha t2', [v('D', 'theta (rad)'), v('U', 'w0 (rad/s)'), v('A', 'alpha rad/s2'), v('T', 't (s)')],
          { D: 'U*T+.5*A*T^^2', U: '(D-.5*A*T^^2)/T', A: '2*(D-U*T)/T^^2', T: 'solve(U*T+.5*A*T^^2-D,T,1)' },
          ['Angle turned through in time t.', '1 revolution = 2 pi radians.']),
        eq('w2', 'w2=w02+2a th', 'w2 = w02 + 2 alpha theta', [v('W', 'w (rad/s)'), v('U', 'w0 (rad/s)'), v('A', 'alpha rad/s2'), v('D', 'theta (rad)')],
          { W: 'sqrt(U^^2+2*A*D)', U: 'sqrt(W^^2-2*A*D)', A: '(W^^2-U^^2)/(2*D)', D: '(W^^2-U^^2)/(2*A)' },
          ['Angular version of v2 = v02 + 2 a dx.']),
        eq('vrw', 'v=r w', 'v = r w', [v('V', 'v (m/s)'), v('R', 'r (m)'), v('W', 'w (rad/s)')],
          { V: 'R*W', R: 'V/W', W: 'V/R' },
          ['Tangential speed of a point at radius r. Also true for rolling without slipping (v of the center).']),
        eq('ara', 'a=r alpha', 'a = r alpha', [v('A', 'a (m/s2)'), v('R', 'r (m)'), v('L', 'alpha rad/s2')],
          { A: 'R*L', R: 'A/L', L: 'A/R' },
          ['Tangential acceleration of a point at radius r.']),
        eq('torque', 'Torque=rF sin', 'torque = r F sin(theta)', [v('T', 'torque (N m)'), v('R', 'r (m)'), v('F', 'F (N)'), v('Q', 'angle (deg)')],
          { T: 'R*F*sin(Q)', R: 'T/(F*sin(Q))', F: 'T/(R*sin(Q))', Q: 'sin^-1(T/(R*F))' },
          ['Torque about a pivot. r is distance from pivot to where the force acts, theta the angle between r and F.'], 'deg'),
        eq('tia', 'Torque=I alpha', 'torque = I alpha', [v('T', 'torque (N m)'), v('I', 'I (kg m2)'), v('A', 'alpha rad/s2')],
          { T: 'I*A', I: 'T/A', A: 'T/I' },
          ["Newton's 2nd law for rotation. Net torque over rotational inertia."]),
        eq('inertia', 'I=c m r2', 'I = c m r2', [v('I', 'I (kg m2)'), v('C', 'c (shape)'), v('M', 'm (kg)'), v('R', 'r (m)')],
          { I: 'C*M*R^^2', C: 'I/(M*R^^2)', M: 'I/(C*R^^2)', R: 'sqrt(I/(C*M))' },
          ['Rotational inertia of common shapes. c = 1 point mass or hoop, .5 disk or solid cylinder, .4 solid sphere, .667 hollow sphere, .0833 rod about center, .333 rod about end.']),
        eq('liw', 'L=I w', 'L = I w', [v('L', 'L (kg m2/s)'), v('I', 'I (kg m2)'), v('W', 'w (rad/s)')],
          { L: 'I*W', I: 'L/W', W: 'L/I' },
          ['Angular momentum of a rotating rigid body.']),
        eq('lmvr', 'L=m v r', 'L = m v r', [v('L', 'L (kg m2/s)'), v('M', 'm (kg)'), v('V', 'v (m/s)'), v('R', 'r (m)')],
          { L: 'M*V*R', M: 'L/(V*R)', V: 'L/(M*R)', R: 'L/(M*V)' },
          ['Angular momentum of a point mass moving perpendicular to r about a point.']),
        eq('kerot', 'KErot=.5Iw2', 'KE rot = .5 I w2', [v('K', 'KE (J)'), v('I', 'I (kg m2)'), v('W', 'w (rad/s)')],
          { K: '.5*I*W^^2', I: '2*K/W^^2', W: 'sqrt(2*K/I)' },
          ['Rotational kinetic energy. Rolling objects have both .5mv2 and .5Iw2.']),
        eq('paxis', 'Parallel axis', 'I = Icm + m d2', [v('I', 'I (kg m2)'), v('C', 'Icm (kg m2)'), v('M', 'm (kg)'), v('D', 'd (m)')],
          { I: 'C+M*D^^2', C: 'I-M*D^^2', M: '(I-C)/D^^2', D: 'sqrt((I-C)/M)' },
          ['Rotational inertia about an axis a distance d from a parallel axis through the center of mass.']),
        {
          id: 'roll', menu: 'Rolling KE', display: 'KE = .5 m v2 (1 + c)',
          vars: [v('M', 'm (kg)'), v('V', 'v (m/s)'), v('C', 'c (shape)')],
          compute: { inputs: ['M', 'V', 'C'], outputs: [{ sym: 'K', name: 'KE total (J)', expr: '.5*M*V^^2*(1+C)' }] },
          notes: ['Total kinetic energy of an object rolling without slipping, I = c m r2.', 'Rolling down a ramp: mgh = .5mv2(1+c), so v = sqrt(2gh/(1+c)).'],
        },
      ],
    },
    {
      id: 'shm',
      menu: 'Oscillations',
      notes: [
        'Simple harmonic motion: restoring force proportional to displacement.',
        'Period of a mass-spring does not depend on amplitude or g.',
        'Period of a pendulum does not depend on mass or amplitude (small angles).',
        'Energy trades between kinetic (max at center) and potential (max at ends).',
      ],
      equations: [
        eq('tspring', 'Spring T', 'T = 2 pi sqrt(m/k)', [v('T', 'T (s)'), v('M', 'm (kg)'), v('K', 'k (N/m)')],
          { T: '2*pi*sqrt(M/K)', M: 'K*(T/(2*pi))^^2', K: 'M*(2*pi/T)^^2' },
          ['Period of a mass on a spring.', 'Stiffer spring: shorter period. More mass: longer period.']),
        eq('tpend', 'Pendulum T', 'T = 2 pi sqrt(L/g)', [v('T', 'T (s)'), v('L', 'L (m)')],
          { T: '2*pi*sqrt(L/G)', L: 'G*(T/(2*pi))^^2' },
          ['Period of a simple pendulum for small swings.', 'Uses g from Settings.']),
        eq('freq', 'f=1/T', 'f = 1 / T', [v('F', 'f (Hz)'), v('T', 'T (s)')],
          { F: '1/T', T: '1/F' },
          ['Frequency in hertz (cycles per second) is the inverse of the period.']),
        eq('omega', 'w=2 pi f', 'w = 2 pi f', [v('W', 'w (rad/s)'), v('F', 'f (Hz)')],
          { W: '2*pi*F', F: 'W/(2*pi)' },
          ['Angular frequency in rad/s. Also w = 2 pi / T and w = sqrt(k/m).']),
        {
          id: 'shmx', menu: 'x,v,a at t', display: 'x = A cos(w t)',
          vars: [v('A', 'A (m)'), v('W', 'w (rad/s)'), v('T', 't (s)')], mode: 'rad',
          compute: { inputs: ['A', 'W', 'T'], outputs: [{ sym: 'X', name: 'x (m)', expr: 'A*cos(W*T)' }, { sym: 'V', name: 'v (m/s)', expr: '~A*W*sin(W*T)' }, { sym: 'C', name: 'a (m/s2)', expr: '~A*W^^2*cos(W*T)' }] },
          notes: ['Position, velocity and acceleration for an oscillator released from x = A at t = 0.', 'Uses radians. w = 2 pi / T.'],
        },
        {
          id: 'shmmax', menu: 'vmax, amax', display: 'vmax = A w, amax = A w2',
          vars: [v('A', 'A (m)'), v('W', 'w (rad/s)')],
          compute: { inputs: ['A', 'W'], outputs: [{ sym: 'V', name: 'vmax (m/s)', expr: 'A*W' }, { sym: 'C', name: 'amax (m/s2)', expr: 'A*W^^2' }] },
          notes: ['Maximum speed occurs at the center; maximum acceleration at the extremes.'],
        },
        eq('eshm', 'E=.5kA2', 'E total = .5 k A2', [v('E', 'E (J)'), v('K', 'k (N/m)'), v('A', 'A (m)')],
          { E: '.5*K*A^^2', K: '2*E/A^^2', A: 'sqrt(2*E/K)' },
          ['Total mechanical energy of a mass-spring oscillator with amplitude A.', 'Also equals .5 m vmax2.']),
      ],
    },
    {
      id: 'fluids',
      menu: 'Fluids',
      notes: [
        'Pressure increases with depth: P = P0 + rho g h.',
        'Buoyant force = weight of displaced fluid.',
        'Continuity: narrower pipe, faster flow.',
        'Bernoulli: faster flow means lower pressure (same height).',
        'Water: rho = 1000 kg/m3. Air pressure P0 = 1.01E5 Pa.',
      ],
      equations: [
        eq('rho', 'rho=m/V', 'rho = m / V', [v('D', 'rho (kg/m3)'), v('M', 'm (kg)'), v('V', 'V (m3)')],
          { D: 'M/V', M: 'D*V', V: 'M/D' },
          ['Density. Water is 1000 kg/m3.', '1 L = 0.001 m3.']),
        eq('pfa', 'P=F/A', 'P = F / A', [v('P', 'P (Pa)'), v('F', 'F (N)'), v('A', 'A (m2)')],
          { P: 'F/A', F: 'P*A', A: 'F/P' },
          ['Pressure is force per area. 1 Pa = 1 N/m2.']),
        eq('pdepth', 'P=P0+rho g h', 'P = P0 + rho g h', [v('P', 'P (Pa)'), v('Q', 'P0 (Pa)'), v('D', 'rho (kg/m3)'), v('H', 'h (m)')],
          { P: 'Q+D*G*H', Q: 'P-D*G*H', D: '(P-Q)/(G*H)', H: '(P-Q)/(D*G)' },
          ['Absolute pressure at depth h. P0 is the pressure at the surface (1.01E5 Pa for open air).', 'Gauge pressure is just rho g h.']),
        eq('buoy', 'Fb=rho V g', 'Fb = rho V g', [v('F', 'Fb (N)'), v('D', 'rho (kg/m3)'), v('V', 'V sub (m3)')],
          { F: 'D*V*G', D: 'F/(V*G)', V: 'F/(D*G)' },
          ["Archimedes: buoyant force equals the weight of fluid displaced.", 'rho is the FLUID density, V the submerged volume. Floating: Fb = weight.']),
        eq('cont', 'A1v1=A2v2', 'A1 v1 = A2 v2', [v('A', 'A1 (m2)'), v('V', 'v1 (m/s)'), v('B', 'A2 (m2)'), v('W', 'v2 (m/s)')],
          { A: 'B*W/V', V: 'B*W/A', B: 'A*V/W', W: 'A*V/B' },
          ['Continuity for an incompressible fluid: volume flow rate is the same everywhere in the pipe.']),
        eq('flow', 'Q=A v', 'Q = A v', [v('Q', 'Q (m3/s)'), v('A', 'A (m2)'), v('V', 'v (m/s)')],
          { Q: 'A*V', A: 'Q/V', V: 'Q/A' },
          ['Volume flow rate: volume passing per second.']),
        eq('bern', 'Bernoulli', 'P1+rho g y1+.5rho v12=..', [v('P', 'P1 (Pa)'), v('Y', 'y1 (m)'), v('V', 'v1 (m/s)'), v('Q', 'P2 (Pa)'), v('Z', 'y2 (m)'), v('W', 'v2 (m/s)'), v('D', 'rho (kg/m3)')],
          { Q: 'P+D*G*(Y-Z)+.5*D*(V^^2-W^^2)', W: 'sqrt(V^^2+2*(P-Q)/D+2*G*(Y-Z))', P: 'Q+D*G*(Z-Y)+.5*D*(W^^2-V^^2)', V: 'sqrt(W^^2+2*(Q-P)/D+2*G*(Z-Y))' },
          ["Bernoulli's equation between points 1 and 2 of a streamline: P + rho g y + .5 rho v2 is constant.", 'Solve for a pressure or a speed; the other five quantities are inputs.']),
        eq('torr', 'Torricelli', 'v = sqrt(2 g h)', [v('V', 'v (m/s)'), v('H', 'h (m)')],
          { V: 'sqrt(2*G*H)', H: 'V^^2/(2*G)' },
          ['Speed of fluid leaving a small hole a depth h below the surface of an open tank.']),
      ],
    },
    {
      id: 'ref',
      menu: 'Constants',
      notes: [
        'g = 9.8 m/s2 (Earth surface)',
        'G = 6.67E-11 N m2/kg2',
        'Earth: M = 5.97E24 kg, R = 6.37E6 m',
        'Moon: M = 7.35E22 kg, R = 1.74E6 m',
        'Sun: M = 1.99E30 kg',
        'Water density 1000 kg/m3',
        'Air pressure 1.01E5 Pa',
        '1 mile = 1609 m, 1 mph = .447 m/s',
        '1 rev = 2 pi rad = 360 deg',
        '1 hp = 746 W, 1 kWh = 3.6E6 J',
      ],
      equations: [],
    },
  ],
};
