// AP Precalculus (College Board units 1-4) as an interactive solver + notes program.
import type { Equation, Subject, Variable } from '../types';

const v = (sym: string, name: string): Variable => ({ sym, name });

function eq(id: string, menu: string, display: string, vars: Variable[], solve: Record<string, string>, notes: string[], mode?: 'deg' | 'rad'): Equation {
  return { id, menu, display, vars, solve, notes, mode };
}
function cmp(id: string, menu: string, display: string, inputs: Variable[], outputs: { sym: string; name: string; expr: string }[], notes: string[], opts: { mode?: 'deg' | 'rad'; code?: string[]; check?: boolean } = {}): Equation {
  return { id, menu, display, vars: inputs, compute: { inputs: inputs.map((i) => i.sym), outputs, code: opts.code }, notes, mode: opts.mode, check: opts.check };
}

/** Prompt for f(x) as text and load it into Y1 so the rest of the block can evaluate it. */
const LOAD_F = ['Input "f(x)=",Str1', 'String>Equ(Str1,{Y1})'];

export const precalc: Subject = {
  program: 'PRECALC',
  title: 'AP PRECALCULUS',
  description:
    'Solvers and notes for all four AP Precalculus units: polynomial and rational functions, exponentials and logarithms, trigonometry and polar coordinates, and parameters, vectors and matrices. Includes function tools that evaluate any f(x) you type.',
  intro: [
    'AP PRECALCULUS',
    'Pick a unit, then a formula. SOLVE asks for the knowns and computes the unknown. NOTES explains the idea.',
    'Function tools ask you to type f(x) using X, for example X^2-3X+2. They store it in Y1.',
  ],
  topics: [
    {
      id: 'poly',
      menu: 'Polynomials',
      notes: [
        'End behavior follows the leading term: even degree, positive lead: up both sides.',
        'A zero of multiplicity 2 touches the axis; odd multiplicity crosses it.',
        'Rational f = p/q: vertical asymptote where q = 0 (and p is not 0); a hole where both are 0.',
        'Horizontal asymptote: deg p < deg q gives y = 0; equal degrees gives ratio of leading coefficients; deg p = deg q + 1 gives a slant asymptote (divide).',
        'Even: f(-x) = f(x). Odd: f(-x) = -f(x).',
        'Transformations: a f(b(x - h)) + k. a stretches vertically, b compresses horizontally, h shifts right, k shifts up.',
        'Inverse: swap x and y and solve; graph reflects over y = x.',
      ],
      equations: [
        cmp('quad', 'Quadratic', 'ax2 + bx + c = 0', [v('A', 'a'), v('B', 'b'), v('C', 'c')],
          [{ sym: 'D', name: 'discriminant', expr: 'B^^2-4*A*C' }, { sym: 'X', name: 'x1 (or real)', expr: '' }, { sym: 'Y', name: 'x2 (or imag)', expr: '' }],
          ['x = (-b +/- sqrt(b2 - 4ac)) / 2a.', 'D > 0: two real roots. D = 0: one repeated root. D < 0: complex roots real +/- imag i; the program then shows the real and imaginary parts.'],
          { code: ['B^^2-4*A*C->D', 'If D>=0', 'Then', '(~B+sqrt(D))/(2*A)->X', '(~B-sqrt(D))/(2*A)->Y', 'Else', '~B/(2*A)->X', 'sqrt(~D)/(2*A)->Y', 'End'] }),
        cmp('vertex', 'Vertex form', 'y = a(x-h)2 + k', [v('A', 'a'), v('B', 'b'), v('C', 'c')],
          [{ sym: 'H', name: 'h (vertex x)', expr: '~B/(2*A)' }, { sym: 'K', name: 'k (vertex y)', expr: 'C-B^^2/(4*A)' }],
          ['Vertex of y = ax2 + bx + c is at x = -b/2a. Axis of symmetry x = h.', 'a > 0: minimum at the vertex. a < 0: maximum.']),
        cmp('avgrate', 'Avg rate f(x)', 'rate=(f(b)-f(a))/(b-a)', [v('A', 'a'), v('B', 'b')],
          [{ sym: 'R', name: 'avg rate', expr: '' }],
          ['Average rate of change of f over [a, b] is the slope of the secant line.', 'Type f(x) with X, e.g. X^2-3X+2. It is stored in Y1.'],
          { code: [...LOAD_F, '({Y1}(B)-{Y1}(A))/(B-A)->R'], check: false }),
        cmp('feval', 'Evaluate f(x)', 'f(x) at x', [v('X', 'x')],
          [{ sym: 'F', name: 'f(x)', expr: '' }],
          ['Evaluates the function you type at the given x. The function is stored in Y1 for graphing.'],
          { code: [...LOAD_F, '{Y1}(X)->F'], check: false }),
        cmp('zero', 'Zero of f(x)', 'f(x) = 0 near a guess', [v('G', 'guess')],
          [{ sym: 'Z', name: 'zero', expr: '' }],
          ['Finds a zero of the function you type, starting from your guess. Different guesses find different zeros.', 'Check with the graph: 2nd, calc, zero.'],
          { code: [...LOAD_F, 'solve({Y1},X,G)->Z'], check: false }),
        cmp('binom', 'Binomial term', '(a+b)^n term k', [v('N', 'n'), v('K', 'k (from 0)'), v('A', 'a'), v('B', 'b')],
          [{ sym: 'C', name: 'coefficient', expr: 'N nCr K' }, { sym: 'T', name: 'term value', expr: '(N nCr K)*A^(N-K)*B^K' }],
          ['(a + b)^n = sum of nCk a^(n-k) b^k for k = 0..n.', 'Coefficients are the rows of Pascal triangle.']),
        eq('arithn', 'Arith. a(n)', 'a(n) = a1 + (n-1)d', [v('A', 'a(n)'), v('F', 'a1'), v('N', 'n'), v('D', 'd')],
          { A: 'F+(N-1)*D', F: 'A-(N-1)*D', N: '(A-F)/D+1', D: '(A-F)/(N-1)' },
          ['Arithmetic sequence: constant difference d. It is a linear function of n.']),
        eq('arithsum', 'Arith. sum Sn', 'Sn = n/2 (2a1 + (n-1)d)', [v('S', 'Sn'), v('F', 'a1'), v('N', 'n'), v('D', 'd')],
          { S: 'N/2*(2*F+(N-1)*D)', F: '(2*S/N-(N-1)*D)/2', D: '(2*S/N-2*F)/(N-1)' },
          ['Sum of the first n terms. Also Sn = n (a1 + an)/2.']),
        eq('geon', 'Geom. a(n)', 'a(n) = a1 r^(n-1)', [v('A', 'a(n)'), v('F', 'a1'), v('N', 'n'), v('R', 'r')],
          { A: 'F*R^(N-1)', F: 'A/R^(N-1)', R: '(A/F)^(1/(N-1))', N: '1+ln(A/F)/ln(R)' },
          ['Geometric sequence: constant ratio r. It is an exponential function of n.']),
        eq('geosum', 'Geom. sum Sn', 'Sn = a1 (1-r^n)/(1-r)', [v('S', 'Sn'), v('F', 'a1'), v('R', 'r'), v('N', 'n')],
          { S: 'F*(1-R^N)/(1-R)', F: 'S*(1-R)/(1-R^N)', N: 'ln(1-S*(1-R)/F)/ln(R)' },
          ['Sum of the first n terms of a geometric sequence, r not 1.']),
        eq('geoinf', 'Geom. infinite', 'S = a1 / (1-r), abs(r)<1', [v('S', 'S'), v('F', 'a1'), v('R', 'r')],
          { S: 'F/(1-R)', F: 'S*(1-R)', R: '1-F/S' },
          ['Infinite geometric series converges only when |r| < 1.']),
        cmp('dist', 'Distance/mid', 'd=sqrt((x2-x1)2+(y2-y1)2)', [v('A', 'x1'), v('B', 'y1'), v('C', 'x2'), v('D', 'y2')],
          [{ sym: 'L', name: 'distance', expr: 'sqrt((C-A)^^2+(D-B)^^2)' }, { sym: 'M', name: 'midpoint x', expr: '(A+C)/2' }, { sym: 'N', name: 'midpoint y', expr: '(B+D)/2' }, { sym: 'S', name: 'slope', expr: '(D-B)/(C-A)' }],
          ['Distance, midpoint and slope between two points.']),
        cmp('line2', 'Line 2 points', 'y = mx + b', [v('A', 'x1'), v('B', 'y1'), v('C', 'x2'), v('D', 'y2')],
          [{ sym: 'M', name: 'slope m', expr: '(D-B)/(C-A)' }, { sym: 'K', name: 'y-intercept b', expr: 'B-(D-B)/(C-A)*A' }],
          ['Slope-intercept form of the line through two points.', 'Point-slope form: y - y1 = m(x - x1).']),
      ],
    },
    {
      id: 'exp',
      menu: 'Exp & Logs',
      notes: [
        'Exponential: constant ratio over equal x steps. Linear: constant difference. Quadratic: constant second difference.',
        'log_b(x) = y means b^y = x. log(xy) = log x + log y. log(x/y) = log x - log y. log(x^n) = n log x.',
        'Change of base: log_b(x) = ln(x)/ln(b).',
        'Regression on the calculator: STAT, EDIT lists, then STAT, CALC: ExpReg (y=ab^x), LnReg, LogReg, PwrReg. Turn on DiagnosticOn for r.',
        'Semi-log plot (log y vs x) is linear when the data is exponential.',
      ],
      equations: [
        eq('expfn', 'y = a b^x', 'y = a b^x', [v('Y', 'y'), v('A', 'a (start)'), v('B', 'b (factor)'), v('X', 'x')],
          { Y: 'A*B^X', A: 'Y/B^X', B: '(Y/A)^(1/X)', X: 'ln(Y/A)/ln(B)' },
          ['Exponential function. b > 1 growth, 0 < b < 1 decay. Percent rate r gives b = 1 + r.']),
        eq('compound', 'Compound int.', 'A = P(1 + r/n)^(nt)', [v('A', 'A (final)'), v('P', 'P (start)'), v('R', 'r (decimal)'), v('N', 'n per year'), v('T', 't (years)')],
          { A: 'P*(1+R/N)^(N*T)', P: 'A/(1+R/N)^(N*T)', T: 'ln(A/P)/(N*ln(1+R/N))', R: 'N*((A/P)^(1/(N*T))-1)' },
          ['Compound interest n times per year. n = 12 monthly, 4 quarterly, 365 daily.']),
        eq('cont', 'A = P e^(rt)', 'A = P e^(rt)', [v('A', 'A (final)'), v('P', 'P (start)'), v('R', 'r (decimal)'), v('T', 't')],
          { A: 'P*e^^(R*T)', P: 'A/e^^(R*T)', R: 'ln(A/P)/T', T: 'ln(A/P)/R' },
          ['Continuous growth or decay. Natural base e = 2.71828.']),
        eq('half', 'Half-life', 'N = N0 (1/2)^(t/h)', [v('N', 'N (final)'), v('A', 'N0 (start)'), v('T', 't'), v('H', 'half-life')],
          { N: 'A*.5^(T/H)', A: 'N/.5^(T/H)', T: 'H*ln(N/A)/ln(.5)', H: 'T*ln(.5)/ln(N/A)' },
          ['Exponential decay expressed with the half-life h.']),
        eq('double', 'Doubling time', 'N = N0 2^(t/d)', [v('N', 'N (final)'), v('A', 'N0 (start)'), v('T', 't'), v('D', 'doubling time')],
          { N: 'A*2^(T/D)', A: 'N/2^(T/D)', T: 'D*ln(N/A)/ln(2)', D: 'T*ln(2)/ln(N/A)' },
          ['Exponential growth expressed with the doubling time d.']),
        cmp('logb', 'log base b', 'log_b(x) = ln x / ln b', [v('B', 'base b'), v('X', 'x')],
          [{ sym: 'L', name: 'log_b(x)', expr: 'ln(X)/ln(B)' }],
          ['Change of base formula. The calculator also has logBASE( in MATH.']),
        cmp('solveexp', 'Solve b^x = c', 'x = ln c / ln b', [v('B', 'b'), v('C', 'c')],
          [{ sym: 'X', name: 'x', expr: 'ln(C)/ln(B)' }],
          ['Take a log of both sides: x ln b = ln c.']),
        cmp('rate2', 'Rate: 2 points', 'b = (y2/y1)^(1/(x2-x1))', [v('A', 'x1'), v('B', 'y1'), v('C', 'x2'), v('D', 'y2')],
          [{ sym: 'R', name: 'growth factor b', expr: '(D/B)^(1/(C-A))' }, { sym: 'P', name: 'percent rate', expr: '100*((D/B)^(1/(C-A))-1)' }, { sym: 'K', name: 'a (value at 0)', expr: 'B/(D/B)^(A/(C-A))' }],
          ['Fit y = a b^x through two points.']),
      ],
    },
    {
      id: 'trig',
      menu: 'Trigonometry',
      notes: [
        'Unit circle: sin 30 = 1/2, sin 45 = sqrt2/2, sin 60 = sqrt3/2; cos is the reverse. tan 45 = 1.',
        'Radians: 30 = pi/6, 45 = pi/4, 60 = pi/3, 90 = pi/2, 180 = pi.',
        'Pythagorean: sin2 + cos2 = 1, 1 + tan2 = sec2, 1 + cot2 = csc2.',
        'Double angle: sin 2x = 2 sin x cos x; cos 2x = cos2 x - sin2 x = 2cos2 x - 1 = 1 - 2sin2 x.',
        'Sum: sin(a+b) = sin a cos b + cos a sin b; cos(a+b) = cos a cos b - sin a sin b.',
        'Inverse ranges: sin^-1 and tan^-1 give -90..90, cos^-1 gives 0..180.',
        'General solutions repeat every 360 (sin, cos) or 180 (tan). Check the quadrant.',
        'y = A sin(B(x - C)) + D: amplitude |A|, period 2pi/B, phase shift C, midline D.',
      ],
      equations: [
        cmp('d2r', 'Degrees to rad', 'rad = deg pi/180', [v('D', 'degrees')], [{ sym: 'R', name: 'radians', expr: 'D*pi/180' }], ['180 degrees = pi radians.']),
        cmp('r2d', 'Rad to degrees', 'deg = rad 180/pi', [v('R', 'radians')], [{ sym: 'D', name: 'degrees', expr: 'R*180/pi' }], ['1 radian = 57.3 degrees.']),
        eq('arc', 'Arc length', 's = r theta (rad)', [v('S', 's (arc)'), v('R', 'r'), v('Q', 'angle (rad)')],
          { S: 'R*Q', R: 'S/Q', Q: 'S/R' },
          ['Arc length with the angle in radians.']),
        eq('sector', 'Sector area', 'A = .5 r2 theta (rad)', [v('K', 'area'), v('R', 'r'), v('Q', 'angle (rad)')],
          { K: '.5*R^^2*Q', R: 'sqrt(2*K/Q)', Q: '2*K/R^^2' },
          ['Area of a circular sector, angle in radians.']),
        cmp('rt1', 'Right tri legs', 'from adjacent, opposite', [v('A', 'adjacent'), v('O', 'opposite')],
          [{ sym: 'H', name: 'hypotenuse', expr: 'sqrt(A^^2+O^^2)' }, { sym: 'Q', name: 'angle (deg)', expr: 'tan^-1(O/A)' }],
          ['SOH CAH TOA. The angle is the one between the adjacent side and the hypotenuse.'], { mode: 'deg' }),
        cmp('rt2', 'Right tri: hyp', 'from hypotenuse, angle', [v('H', 'hypotenuse'), v('Q', 'angle (deg)')],
          [{ sym: 'A', name: 'adjacent', expr: 'H*cos(Q)' }, { sym: 'O', name: 'opposite', expr: 'H*sin(Q)' }],
          ['adjacent = h cos(theta), opposite = h sin(theta).'], { mode: 'deg' }),
        eq('lawsin', 'Law of sines', 'a/sin A = b/sin B', [v('A', 'side a'), v('B', 'angle A (deg)'), v('C', 'side b'), v('D', 'angle B (deg)')],
          { A: 'C*sin(B)/sin(D)', C: 'A*sin(D)/sin(B)', B: 'sin^-1(A*sin(D)/C)', D: 'sin^-1(C*sin(B)/A)' },
          ['Use with two angles and a side, or two sides and an opposite angle.', 'Ambiguous case: an angle found with sin^-1 may also be 180 minus that value.'], 'deg'),
        eq('lawcos', 'Law of cosines', 'c2 = a2 + b2 - 2ab cos C', [v('C', 'side c'), v('A', 'side a'), v('B', 'side b'), v('Q', 'angle C (deg)')],
          { C: 'sqrt(A^^2+B^^2-2*A*B*cos(Q))', Q: 'cos^-1((A^^2+B^^2-C^^2)/(2*A*B))', A: 'B*cos(Q)+sqrt((B*cos(Q))^^2-B^^2+C^^2)', B: 'A*cos(Q)+sqrt((A*cos(Q))^^2-A^^2+C^^2)' },
          ['Use with three sides (find an angle) or two sides and the included angle (find the third side).'], 'deg'),
        eq('triarea', 'Area .5ab sinC', 'K = .5 a b sin C', [v('K', 'area'), v('A', 'side a'), v('B', 'side b'), v('Q', 'angle C (deg)')],
          { K: '.5*A*B*sin(Q)', A: '2*K/(B*sin(Q))', B: '2*K/(A*sin(Q))', Q: 'sin^-1(2*K/(A*B))' },
          ['Area from two sides and the included angle.'], 'deg'),
        cmp('heron', "Heron's area", 'K = sqrt(s(s-a)(s-b)(s-c))', [v('A', 'side a'), v('B', 'side b'), v('C', 'side c')],
          [{ sym: 'S', name: 'semi-perimeter', expr: '(A+B+C)/2' }, { sym: 'K', name: 'area', expr: 'sqrt((A+B+C)/2*((A+B+C)/2-A)*((A+B+C)/2-B)*((A+B+C)/2-C))' }],
          ['Area from three sides. s is half the perimeter.']),
        cmp('sinusoid', 'Sinusoid info', 'y = A sin(B(x-C)) + D', [v('A', 'amplitude A'), v('B', 'B'), v('D', 'midline D')],
          [{ sym: 'P', name: 'period', expr: '2*pi/B' }, { sym: 'M', name: 'maximum', expr: 'D+abs(A)' }, { sym: 'N', name: 'minimum', expr: 'D-abs(A)' }],
          ['Period = 2pi/B in radians. Amplitude = (max - min)/2. Midline = (max + min)/2.']),
        cmp('bfromp', 'B from period', 'B = 2 pi / period', [v('P', 'period')], [{ sym: 'B', name: 'B', expr: '2*pi/P' }], ['Frequency is 1/period.']),
        cmp('p2r', 'Polar to (x,y)', 'x = r cos, y = r sin', [v('R', 'r'), v('Q', 'angle (deg)')],
          [{ sym: 'X', name: 'x', expr: 'R*cos(Q)' }, { sym: 'Y', name: 'y', expr: 'R*sin(Q)' }],
          ['Polar coordinates (r, theta) to rectangular.'], { mode: 'deg' }),
        cmp('r2p', '(x,y) to polar', 'r = sqrt(x2+y2)', [v('X', 'x'), v('Y', 'y')],
          [{ sym: 'R', name: 'r', expr: 'sqrt(X^^2+Y^^2)' }, { sym: 'Q', name: 'angle (deg)', expr: 'tan^-1(Y/X)' }],
          ['tan^-1 returns -90..90: add 180 when x is negative.'], { mode: 'deg' }),
      ],
    },
    {
      id: 'vec',
      menu: 'Vectors/Matrix',
      notes: [
        'Parametric: x = f(t), y = g(t). Eliminate t to get a rectangular equation.',
        'Vectors add tip to tail; components add separately. Magnitude = sqrt(x2 + y2).',
        'Dot product u.v = (mag u)(mag v) cos theta; zero means perpendicular.',
        'Matrix times vector is a linear transformation; the determinant is the area scale factor.',
        'Inverse of a 2x2 [[a,b],[c,d]] = 1/det [[d,-b],[-c,a]].',
        'Conics: circle (x-h)2+(y-k)2=r2; ellipse x2/a2+y2/b2=1; hyperbola x2/a2-y2/b2=1; parabola y=a(x-h)2+k.',
      ],
      equations: [
        cmp('vmag', 'Vector mag/dir', 'mag = sqrt(x2+y2)', [v('X', 'x component'), v('Y', 'y component')],
          [{ sym: 'M', name: 'magnitude', expr: 'sqrt(X^^2+Y^^2)' }, { sym: 'Q', name: 'angle (deg)', expr: 'tan^-1(Y/X)' }],
          ['Magnitude and direction of a vector. Add 180 to the angle when x is negative.'], { mode: 'deg' }),
        cmp('vcomp', 'Vector comps', 'x = mag cos, y = mag sin', [v('M', 'magnitude'), v('Q', 'angle (deg)')],
          [{ sym: 'X', name: 'x component', expr: 'M*cos(Q)' }, { sym: 'Y', name: 'y component', expr: 'M*sin(Q)' }],
          ['Components from magnitude and direction.'], { mode: 'deg' }),
        cmp('dot', 'Dot & angle', 'u.v=(mag u)(mag v)cos', [v('A', 'u x'), v('B', 'u y'), v('C', 'v x'), v('D', 'v y')],
          [{ sym: 'P', name: 'u dot v', expr: 'A*C+B*D' }, { sym: 'Q', name: 'angle (deg)', expr: 'cos^-1((A*C+B*D)/(sqrt(A^^2+B^^2)*sqrt(C^^2+D^^2)))' }],
          ['Dot product and the angle between two vectors.'], { mode: 'deg' }),
        cmp('det2', '2x2 det & inv', 'det = ad - bc', [v('A', 'a'), v('B', 'b'), v('C', 'c'), v('D', 'd')],
          [{ sym: 'E', name: 'determinant', expr: 'A*D-B*C' }, { sym: 'W', name: 'inv [1,1]', expr: 'D/(A*D-B*C)' }, { sym: 'X', name: 'inv [1,2]', expr: '~B/(A*D-B*C)' }, { sym: 'Y', name: 'inv [2,1]', expr: '~C/(A*D-B*C)' }, { sym: 'Z', name: 'inv [2,2]', expr: 'A/(A*D-B*C)' }],
          ['Matrix [[a,b],[c,d]]. No inverse when the determinant is 0.']),
        cmp('sys2', '2x2 system', 'ax+by=e, cx+dy=f', [v('A', 'a'), v('B', 'b'), v('E', 'e'), v('C', 'c'), v('D', 'd'), v('F', 'f')],
          [{ sym: 'X', name: 'x', expr: '(E*D-B*F)/(A*D-B*C)' }, { sym: 'Y', name: 'y', expr: '(A*F-E*C)/(A*D-B*C)' }],
          ["Cramer's rule. No unique solution when ad - bc = 0 (parallel or identical lines)."]),
        cmp('matmul', '2x2 multiply', '[A][B] entries', [v('A', 'A[1,1]'), v('B', 'A[1,2]'), v('C', 'A[2,1]'), v('D', 'A[2,2]'), v('E', 'B[1,1]'), v('F', 'B[1,2]'), v('G', 'B[2,1]'), v('H', 'B[2,2]')],
          [{ sym: 'W', name: '[1,1]', expr: 'A*E+B*G' }, { sym: 'X', name: '[1,2]', expr: 'A*F+B*H' }, { sym: 'Y', name: '[2,1]', expr: 'C*E+D*G' }, { sym: 'Z', name: '[2,2]', expr: 'C*F+D*H' }],
          ['Row of the first times column of the second. Order matters: AB is not BA.']),
        cmp('param', 'Param. line', 'x=x0+vx t, y=y0+vy t', [v('P', 'x0'), v('Q', 'y0'), v('U', 'vx'), v('V', 'vy'), v('T', 't')],
          [{ sym: 'X', name: 'x(t)', expr: 'P+U*T' }, { sym: 'Y', name: 'y(t)', expr: 'Q+V*T' }],
          ['Position at time t along a line. Slope of the path is vy/vx.']),
      ],
    },
    {
      id: 'ref',
      menu: 'Formulas',
      notes: [
        'Quadratic: x = (-b +/- sqrt(b2-4ac))/2a',
        'Vertex x = -b/2a',
        'Distance sqrt((dx)2+(dy)2)',
        'Arithmetic: a(n) = a1+(n-1)d',
        'Geometric: a(n) = a1 r^(n-1)',
        'Compound: A = P(1+r/n)^(nt)',
        'Continuous: A = P e^(rt)',
        'log_b x = ln x / ln b',
        'Law of sines: a/sinA = b/sinB',
        'Law of cosines: c2 = a2+b2-2ab cosC',
        'Area = .5 ab sin C',
        'Polar: x = r cos t, y = r sin t',
        'det [[a,b],[c,d]] = ad - bc',
      ],
      equations: [],
    },
  ],
};
