// AP Statistics: formulas, test statistics, intervals and "which test" guidance.
import type { Equation, Subject, Variable } from '../types';

const v = (sym: string, name: string): Variable => ({ sym, name });

function eq(id: string, menu: string, display: string, vars: Variable[], solve: Record<string, string>, notes: string[]): Equation {
  return { id, menu, display, vars, solve, notes };
}
function cmp(id: string, menu: string, display: string, inputs: Variable[], outputs: { sym: string; name: string; expr: string }[], notes: string[], opts: { code?: string[]; check?: boolean } = {}): Equation {
  return { id, menu, display, vars: inputs, compute: { inputs: inputs.map((i) => i.sym), outputs, code: opts.code }, notes, check: opts.check };
}

const INF = '1|E99';
const ZSTAR = 'invNorm(1-(1-C)/2)';

export const stats: Subject = {
  program: 'STATS',
  title: 'AP STATISTICS',
  description:
    'Every AP Statistics formula with a calculator: z-scores, normal and binomial probabilities, sampling distributions, confidence intervals and test statistics with p-values for proportions, means, chi-square and regression slope, plus notes on conditions, interpretation and which test to use.',
  intro: [
    'AP STATISTICS',
    'Pick a unit, then a tool. Confidence levels are decimals: .95 for 95%. Use 1E99 for infinity in bounds.',
    'NOTES give conditions, interpretation sentences and the matching STAT TESTS menu item.',
  ],
  topics: [
    {
      id: 'one',
      menu: 'One variable',
      notes: [
        'Describe a distribution with SOCS: shape, outliers, center, spread, in context.',
        'Mean and SD for symmetric data; median and IQR when skewed or with outliers.',
        'Calculator: STAT, EDIT to enter data in L1, then STAT, CALC, 1-Var Stats L1.',
        'Adding a constant shifts center, not spread. Multiplying scales both.',
        'Empirical rule (normal): 68% within 1 SD, 95% within 2, 99.7% within 3.',
      ],
      equations: [
        eq('z', 'z-score', 'z = (x - mean)/sd', [v('Z', 'z'), v('X', 'x'), v('M', 'mean'), v('S', 'sd')],
          { Z: '(X-M)/S', X: 'M+Z*S', M: 'X-Z*S', S: '(X-M)/Z' },
          ['How many standard deviations x is from the mean. Unit-free, so z-scores compare different scales.']),
        cmp('z2p', 'z to percent', 'percentile = P(Z < z)', [v('Z', 'z')],
          [{ sym: 'P', name: 'percentile %', expr: '100*normalcdf(~1|E99,Z)' }],
          ['Percent of a normal distribution below z. Calculator: normalcdf(-1E99, z).']),
        cmp('p2z', 'Percent to z', 'z = invNorm(p)', [v('P', 'percentile %')],
          [{ sym: 'Z', name: 'z', expr: 'invNorm(P/100)' }],
          ['z with the given percent of the distribution below it. Calculator: invNorm(area).']),
        cmp('iqr', 'IQR & fences', 'IQR = Q3 - Q1', [v('A', 'Q1'), v('B', 'Q3')],
          [{ sym: 'I', name: 'IQR', expr: 'B-A' }, { sym: 'L', name: 'lower fence', expr: 'A-1.5*(B-A)' }, { sym: 'U', name: 'upper fence', expr: 'B+1.5*(B-A)' }],
          ['Values below Q1 - 1.5 IQR or above Q3 + 1.5 IQR are outliers (1.5 IQR rule).']),
        cmp('emp', 'Empirical rule', '68-95-99.7', [v('M', 'mean'), v('S', 'sd')],
          [{ sym: 'A', name: '68% low', expr: 'M-S' }, { sym: 'B', name: '68% high', expr: 'M+S' }, { sym: 'C', name: '95% low', expr: 'M-2*S' }, { sym: 'D', name: '95% high', expr: 'M+2*S' }, { sym: 'E', name: '99.7% low', expr: 'M-3*S' }, { sym: 'F', name: '99.7% high', expr: 'M+3*S' }],
          ['Ranges holding 68%, 95% and 99.7% of an approximately normal distribution.']),
      ],
    },
    {
      id: 'two',
      menu: 'Two variables',
      notes: [
        'Describe scatterplots with DOFS: direction, outliers, form, strength.',
        'r measures linear strength (-1..1). r2 is the percent of variation in y explained by x.',
        'Calculator: lists in L1 (x) and L2 (y); STAT, CALC, LinReg(a+bx) L1,L2,Y1. DiagnosticOn shows r.',
        'Slope: predicted y changes by b for each 1 unit increase in x. Intercept: predicted y when x = 0.',
        'Residual = actual - predicted. A curved residual plot means a linear model is wrong.',
        'Do not extrapolate beyond the data. Correlation is not causation.',
      ],
      equations: [
        cmp('lsrl', 'LSRL from r,sd', 'b=r sy/sx, a=ybar-b xbar', [v('R', 'r'), v('X', 'sx'), v('Y', 'sy'), v('M', 'mean x'), v('N', 'mean y')],
          [{ sym: 'B', name: 'slope b', expr: 'R*Y/X' }, { sym: 'A', name: 'intercept a', expr: 'N-R*Y/X*M' }, { sym: 'S', name: 'r squared', expr: 'R^^2' }],
          ['Least-squares line from summary statistics. The line always passes through (xbar, ybar).']),
        eq('pred', 'Predict y hat', 'y hat = a + b x', [v('Y', 'y hat'), v('A', 'a'), v('B', 'b'), v('X', 'x')],
          { Y: 'A+B*X', X: '(Y-A)/B', A: 'Y-B*X', B: '(Y-A)/X' },
          ['Predicted value from the regression line.']),
        cmp('resid', 'Residual', 'residual = y - y hat', [v('Y', 'actual y'), v('P', 'predicted y')],
          [{ sym: 'E', name: 'residual', expr: 'Y-P' }],
          ['Positive residual: the line under-predicts.']),
      ],
    },
    {
      id: 'prob',
      menu: 'Probability',
      notes: [
        'Complement: P(not A) = 1 - P(A). Mutually exclusive: P(A and B) = 0.',
        'Independent: P(A and B) = P(A) P(B), and P(A|B) = P(A).',
        'Binomial (BINS): binary outcomes, independent, fixed n, same p. Geometric (BITS): trials until first success.',
        'Calculator: 2nd, DISTR: binompdf(n,p,k), binomcdf(n,p,k), geometpdf(p,k), normalcdf(lo,hi,mean,sd), invNorm(area,mean,sd).',
        'Expected value E(X) = sum of x P(x). Interpret as a long-run average.',
      ],
      equations: [
        eq('add', 'P(A or B)', 'P(AorB)=P(A)+P(B)-P(A&B)', [v('U', 'P(A or B)'), v('A', 'P(A)'), v('B', 'P(B)'), v('I', 'P(A and B)')],
          { U: 'A+B-I', A: 'U-B+I', B: 'U-A+I', I: 'A+B-U' },
          ['General addition rule. For mutually exclusive events P(A and B) = 0.']),
        eq('cond', 'P(A|B)', 'P(A|B) = P(A and B)/P(B)', [v('C', 'P(A|B)'), v('I', 'P(A and B)'), v('B', 'P(B)')],
          { C: 'I/B', I: 'C*B', B: 'I/C' },
          ['Conditional probability: restrict to the cases where B happened.']),
        eq('indep', 'Indep. P(A&B)', 'P(A and B) = P(A) P(B)', [v('I', 'P(A and B)'), v('A', 'P(A)'), v('B', 'P(B)')],
          { I: 'A*B', A: 'I/B', B: 'I/A' },
          ['Multiplication rule for independent events only.']),
        cmp('perm', 'nPr and nCr', 'n!/(n-k)!, n!/(k!(n-k)!)', [v('N', 'n'), v('K', 'k')],
          [{ sym: 'P', name: 'nPr (ordered)', expr: 'N nPr K' }, { sym: 'C', name: 'nCr (unordered)', expr: 'N nCr K' }],
          ['Permutations count arrangements; combinations count selections.']),
        cmp('binom', 'Binomial', 'X ~ B(n, p)', [v('N', 'n'), v('P', 'p'), v('K', 'k')],
          [{ sym: 'M', name: 'mean np', expr: 'N*P' }, { sym: 'S', name: 'sd', expr: 'sqrt(N*P*(1-P))' }, { sym: 'A', name: 'P(X = k)', expr: 'binompdf(N,P,K)' }, { sym: 'B', name: 'P(X <= k)', expr: 'binomcdf(N,P,K)' }, { sym: 'C', name: 'P(X >= k)', expr: '1-binomcdf(N,P,K-1)' }],
          ['Number of successes in n independent trials with success probability p.', 'P(X >= k) = 1 - P(X <= k-1).']),
        cmp('geom', 'Geometric', 'P(X=k) = (1-p)^(k-1) p', [v('P', 'p'), v('K', 'k')],
          [{ sym: 'A', name: 'P(X = k)', expr: '(1-P)^(K-1)*P' }, { sym: 'B', name: 'P(X <= k)', expr: '1-(1-P)^K' }, { sym: 'M', name: 'mean 1/p', expr: '1/P' }, { sym: 'S', name: 'sd', expr: 'sqrt(1-P)/P' }],
          ['Trials until the first success.']),
        cmp('ev', 'E(X) via lists', 'E(X) = sum x P(x)', [],
          [{ sym: 'M', name: 'mean E(X)', expr: '' }, { sym: 'S', name: 'sd', expr: '' }],
          ['Put the values in L1 and their probabilities in L2 first (STAT, EDIT).', 'Variance = sum (x - mean)2 P(x).'],
          { code: ['Disp "Values in L1,"', 'Disp "probabilities in L2."', 'Pause ', 'sum(L1*L2)->M', 'sqrt(sum(L1^^2*L2)-M^^2)->S'], check: false }),
        cmp('combine', 'X + Y, X - Y', 'independent X and Y', [v('A', 'mean X'), v('B', 'sd X'), v('C', 'mean Y'), v('D', 'sd Y')],
          [{ sym: 'M', name: 'mean X+Y', expr: 'A+C' }, { sym: 'S', name: 'sd X+Y', expr: 'sqrt(B^^2+D^^2)' }, { sym: 'N', name: 'mean X-Y', expr: 'A-C' }, { sym: 'T', name: 'sd X-Y', expr: 'sqrt(B^^2+D^^2)' }],
          ['Means add or subtract. Variances ALWAYS add (for independent variables), even for X - Y.']),
        cmp('linear', 'aX + b', 'mean a mu+b, sd |a| sigma', [v('A', 'a'), v('B', 'b'), v('M', 'mean X'), v('S', 'sd X')],
          [{ sym: 'N', name: 'mean aX+b', expr: 'A*M+B' }, { sym: 'T', name: 'sd aX+b', expr: 'abs(A)*S' }],
          ['Linear transformation of a random variable.']),
        cmp('normal', 'Normal prob', 'P(a < X < b)', [v('M', 'mean'), v('S', 'sd'), v('A', 'lower a'), v('B', 'upper b')],
          [{ sym: 'P', name: 'probability', expr: 'normalcdf(A,B,M,S)' }],
          ['Use -1E99 or 1E99 for an open end. Calculator: normalcdf(a, b, mean, sd).']),
        cmp('invn', 'Inverse normal', 'x with area p to the left', [v('P', 'area to left'), v('M', 'mean'), v('S', 'sd')],
          [{ sym: 'X', name: 'x', expr: 'invNorm(P,M,S)' }],
          ['Cutoff value for a percentile. Calculator: invNorm(area, mean, sd).']),
      ],
    },
    {
      id: 'samp',
      menu: 'Sampling dist',
      notes: [
        'Sampling distribution: values of a statistic from all possible samples of size n.',
        'p hat: mean p, sd sqrt(p(1-p)/n). Approximately normal when np >= 10 and n(1-p) >= 10.',
        'x bar: mean mu, sd sigma/sqrt(n). Normal if the population is normal or n >= 30 (CLT).',
        '10% condition: sample less than 10% of the population so sd formulas hold.',
        'Unbiased: the mean of the sampling distribution equals the parameter.',
      ],
      equations: [
        cmp('phat', 'p hat dist.', 'mean p, sd sqrt(p(1-p)/n)', [v('P', 'p'), v('N', 'n')],
          [{ sym: 'M', name: 'mean', expr: 'P' }, { sym: 'S', name: 'sd', expr: 'sqrt(P*(1-P)/N)' }, { sym: 'A', name: 'np (>=10?)', expr: 'N*P' }, { sym: 'B', name: 'n(1-p) (>=10?)', expr: 'N*(1-P)' }],
          ['Sampling distribution of a sample proportion.']),
        eq('xbar', 'x bar sd', 'sd = sigma / sqrt(n)', [v('S', 'sd of x bar'), v('G', 'sigma'), v('N', 'n')],
          { S: 'G/sqrt(N)', G: 'S*sqrt(N)', N: '(G/S)^^2' },
          ['Standard deviation of the sample mean shrinks with sqrt(n).']),
        cmp('zxbar', 'z for x bar', 'z=(xbar-mu)/(sigma/sqrt n)', [v('X', 'x bar'), v('M', 'mu'), v('G', 'sigma'), v('N', 'n')],
          [{ sym: 'Z', name: 'z', expr: '(X-M)/(G/sqrt(N))' }, { sym: 'P', name: 'P(below)', expr: 'normalcdf(~1|E99,(X-M)/(G/sqrt(N)))' }],
          ['Probability a sample mean falls below x bar when the population sd is known.']),
        cmp('zphat', 'z for p hat', 'z=(phat-p)/sqrt(p(1-p)/n)', [v('P', 'p hat'), v('Q', 'p'), v('N', 'n')],
          [{ sym: 'Z', name: 'z', expr: '(P-Q)/sqrt(Q*(1-Q)/N)' }, { sym: 'A', name: 'P(below)', expr: 'normalcdf(~1|E99,(P-Q)/sqrt(Q*(1-Q)/N))' }],
          ['Probability a sample proportion falls below p hat.']),
        cmp('dprop', 'sd of p1 - p2', 'sqrt(p1q1/n1 + p2q2/n2)', [v('P', 'p1'), v('N', 'n1'), v('Q', 'p2'), v('M', 'n2')],
          [{ sym: 'S', name: 'sd', expr: 'sqrt(P*(1-P)/N+Q*(1-Q)/M)' }],
          ['Standard deviation of the difference of two independent sample proportions.']),
        cmp('dmean', 'sd of x1 - x2', 'sqrt(s1^2/n1 + s2^2/n2)', [v('A', 'sigma 1'), v('N', 'n1'), v('B', 'sigma 2'), v('M', 'n2')],
          [{ sym: 'S', name: 'sd', expr: 'sqrt(A^^2/N+B^^2/M)' }],
          ['Standard deviation of the difference of two independent sample means.']),
      ],
    },
    {
      id: 'propinf',
      menu: 'Proportions',
      notes: [
        'Conditions: random sample, 10% condition, large counts (np >= 10 and n(1-p) >= 10; use p hat for intervals, p0 for tests).',
        'Interval: "We are 95% confident that the interval from L to U captures the true proportion of ...".',
        'Test: state H0: p = p0 and Ha; compute z and the p-value; if p-value < alpha reject H0 in context.',
        'Calculator: STAT, TESTS: 1-PropZInt, 1-PropZTest, 2-PropZInt, 2-PropZTest.',
        'z*: 90% 1.645, 95% 1.960, 99% 2.576.',
      ],
      equations: [
        cmp('zstar', 'z* from conf.', 'z* = invNorm(1-(1-C)/2)', [v('C', 'confidence')],
          [{ sym: 'Z', name: 'z*', expr: ZSTAR }],
          ['Critical value for a confidence level entered as a decimal, e.g. .95.']),
        cmp('pci', '1-prop z int', 'phat +/- z* sqrt(pq/n)', [v('P', 'p hat'), v('N', 'n'), v('C', 'confidence')],
          [{ sym: 'Z', name: 'z*', expr: ZSTAR }, { sym: 'E', name: 'margin', expr: `${ZSTAR}*sqrt(P*(1-P)/N)` }, { sym: 'L', name: 'lower', expr: `P-${ZSTAR}*sqrt(P*(1-P)/N)` }, { sym: 'U', name: 'upper', expr: `P+${ZSTAR}*sqrt(P*(1-P)/N)` }],
          ['One-sample z interval for a proportion.']),
        cmp('nsize', 'n for margin', 'n = (z*/E)2 p(1-p)', [v('E', 'margin E'), v('C', 'confidence'), v('P', 'p guess (.5)')],
          [{ sym: 'N', name: 'n (round up)', expr: `(${ZSTAR}/E)^^2*P*(1-P)` }],
          ['Sample size needed for a margin of error E. Use p = .5 when no estimate exists (largest n).']),
        cmp('ptest', '1-prop z test', 'z=(phat-p0)/sqrt(p0q0/n)', [v('P', 'p hat'), v('Q', 'p0'), v('N', 'n')],
          [{ sym: 'Z', name: 'z', expr: '(P-Q)/sqrt(Q*(1-Q)/N)' }, { sym: 'A', name: 'p-value 2-sided', expr: `2*normalcdf(abs((P-Q)/sqrt(Q*(1-Q)/N)),${INF})` }, { sym: 'B', name: 'p-value 1-sided', expr: `normalcdf(abs((P-Q)/sqrt(Q*(1-Q)/N)),${INF})` }],
          ['Uses p0 (the null value) in the standard error.']),
        cmp('p2test', '2-prop z test', 'pooled: (x1+x2)/(n1+n2)', [v('X', 'x1 successes'), v('N', 'n1'), v('Y', 'x2 successes'), v('M', 'n2')],
          [{ sym: 'P', name: 'p hat 1', expr: 'X/N' }, { sym: 'Q', name: 'p hat 2', expr: 'Y/M' }, { sym: 'K', name: 'pooled p hat', expr: '(X+Y)/(N+M)' }, { sym: 'Z', name: 'z', expr: '(X/N-Y/M)/sqrt((X+Y)/(N+M)*(1-(X+Y)/(N+M))*(1/N+1/M))' }, { sym: 'A', name: 'p-value 2-sided', expr: `2*normalcdf(abs((X/N-Y/M)/sqrt((X+Y)/(N+M)*(1-(X+Y)/(N+M))*(1/N+1/M))),${INF})` }],
          ['Two-sample z test for p1 - p2 with the pooled proportion in the standard error.']),
        cmp('p2ci', '2-prop z int', '(p1-p2) +/- z* SE', [v('P', 'p hat 1'), v('N', 'n1'), v('Q', 'p hat 2'), v('M', 'n2'), v('C', 'confidence')],
          [{ sym: 'Z', name: 'z*', expr: ZSTAR }, { sym: 'E', name: 'margin', expr: `${ZSTAR}*sqrt(P*(1-P)/N+Q*(1-Q)/M)` }, { sym: 'L', name: 'lower', expr: `(P-Q)-${ZSTAR}*sqrt(P*(1-P)/N+Q*(1-Q)/M)` }, { sym: 'U', name: 'upper', expr: `(P-Q)+${ZSTAR}*sqrt(P*(1-P)/N+Q*(1-Q)/M)` }],
          ['Two-sample z interval for the difference of proportions (unpooled).']),
      ],
    },
    {
      id: 'meaninf',
      menu: 'Means',
      notes: [
        'Conditions: random, 10%, and normal/large sample: population normal, or n >= 30, or a plot with no strong skew/outliers.',
        'Use t whenever sigma is unknown (almost always). df = n - 1.',
        'Paired data: take differences first, then do a one-sample t on the differences.',
        'Two-sample t: independent groups; df from the calculator (Welch) or the conservative min(n1, n2) - 1.',
        'Calculator: STAT, TESTS: TInterval, T-Test, 2-SampTInt, 2-SampTTest (Pooled: No).',
      ],
      equations: [
        cmp('tstar', 't* from C, df', 't* = invT(1-(1-C)/2, df)', [v('C', 'confidence'), v('D', 'df')],
          [{ sym: 'T', name: 't*', expr: '' }],
          ['Critical t value. df = n - 1 for one sample.'],
          { code: ['invT(1-(1-C)/2,D)->T'], check: false }),
        cmp('tci', '1-samp t int', 'xbar +/- t* s/sqrt(n)', [v('X', 'x bar'), v('S', 's'), v('N', 'n'), v('C', 'confidence')],
          [{ sym: 'T', name: 't*', expr: '' }, { sym: 'E', name: 'margin', expr: '' }, { sym: 'L', name: 'lower', expr: '' }, { sym: 'U', name: 'upper', expr: '' }],
          ['One-sample t interval for a mean, df = n - 1.'],
          { code: ['invT(1-(1-C)/2,N-1)->T', 'T*S/sqrt(N)->E', 'X-E->L', 'X+E->U'], check: false }),
        cmp('ttest', '1-samp t test', 't=(xbar-mu0)/(s/sqrt n)', [v('X', 'x bar'), v('M', 'mu0'), v('S', 's'), v('N', 'n')],
          [{ sym: 'T', name: 't', expr: '' }, { sym: 'D', name: 'df', expr: '' }, { sym: 'A', name: 'p-value 2-sided', expr: '' }, { sym: 'B', name: 'p-value 1-sided', expr: '' }],
          ['One-sample t test. Halve the two-sided p-value for a one-sided alternative in the observed direction.'],
          { code: ['(X-M)/(S/sqrt(N))->T', 'N-1->D', `2*tcdf(abs(T),${INF},D)->A`, 'A/2->B'], check: false }),
        cmp('t2test', '2-samp t test', 't=(x1-x2)/SE, SE=sqrt(..)', [v('X', 'x bar 1'), v('S', 's1'), v('N', 'n1'), v('Y', 'x bar 2'), v('R', 's2'), v('M', 'n2')],
          [{ sym: 'T', name: 't', expr: '' }, { sym: 'D', name: 'df (Welch)', expr: '' }, { sym: 'A', name: 'p-value 2-sided', expr: '' }],
          ['Two-sample t test for mu1 - mu2 (not pooled). The df formula matches the calculator.'],
          { code: ['(X-Y)/sqrt(S^^2/N+R^^2/M)->T', '(S^^2/N+R^^2/M)^^2/((S^^2/N)^^2/(N-1)+(R^^2/M)^^2/(M-1))->D', `2*tcdf(abs(T),${INF},D)->A`], check: false }),
        cmp('t2ci', '2-samp t int', '(x1-x2) +/- t* SE', [v('X', 'x bar 1'), v('S', 's1'), v('N', 'n1'), v('Y', 'x bar 2'), v('R', 's2'), v('M', 'n2'), v('C', 'confidence')],
          [{ sym: 'D', name: 'df (Welch)', expr: '' }, { sym: 'T', name: 't*', expr: '' }, { sym: 'E', name: 'margin', expr: '' }, { sym: 'L', name: 'lower', expr: '' }, { sym: 'U', name: 'upper', expr: '' }],
          ['Two-sample t interval for the difference of means.'],
          { code: ['(S^^2/N+R^^2/M)^^2/((S^^2/N)^^2/(N-1)+(R^^2/M)^^2/(M-1))->D', 'invT(1-(1-C)/2,D)->T', 'T*sqrt(S^^2/N+R^^2/M)->E', '(X-Y)-E->L', '(X-Y)+E->U'], check: false }),
      ],
    },
    {
      id: 'chi',
      menu: 'Chi-square',
      notes: [
        'Goodness of fit: one categorical variable vs claimed distribution, df = k - 1. Calculator: chi2 GOF-Test with observed in L1, expected in L2.',
        'Independence/homogeneity: two-way table, df = (rows-1)(cols-1). Calculator: chi2-Test with observed counts in matrix [A]; expected appear in [B].',
        'Conditions: random, 10%, all expected counts >= 5.',
        'Large chi2 (small p-value) means observed counts differ from expected more than chance would explain.',
      ],
      equations: [
        eq('expected', 'Expected count', 'E = row tot x col tot / n', [v('E', 'expected'), v('R', 'row total'), v('C', 'column total'), v('T', 'grand total')],
          { E: 'R*C/T', R: 'E*T/C', C: 'E*T/R', T: 'R*C/E' },
          ['Expected count in a two-way table cell under independence.']),
        cmp('contrib', 'Cell (O-E)2/E', 'component of chi-square', [v('O', 'observed'), v('E', 'expected')],
          [{ sym: 'C', name: 'contribution', expr: '(O-E)^^2/E' }],
          ['Chi-square statistic is the sum of these over all cells.']),
        cmp('chip', 'chi2 p-value', 'P(chi2 > value)', [v('X', 'chi-square'), v('D', 'df')],
          [{ sym: 'P', name: 'p-value', expr: '' }],
          ['Right-tail probability. Calculator: chi2cdf(value, 1E99, df).'],
          { code: [`chi^2cdf(X,${INF},D)->P`], check: false }),
      ],
    },
    {
      id: 'slope',
      menu: 'Slope',
      notes: [
        'Inference for the slope of the population regression line: t = b/SE(b), df = n - 2.',
        'Computer output: Coef column gives a and b; SE Coef gives SE(b); T and P give the test; S is sd of residuals; R-Sq is r2.',
        'Conditions (LINER): linear, independent, normal residuals, equal variance, random.',
        'Calculator: STAT, TESTS: LinRegTTest, LinRegTInt.',
      ],
      equations: [
        cmp('slopet', 't for slope', 't = b / SE(b), df = n-2', [v('B', 'slope b'), v('S', 'SE of b'), v('N', 'n')],
          [{ sym: 'T', name: 't', expr: '' }, { sym: 'D', name: 'df', expr: '' }, { sym: 'A', name: 'p-value 2-sided', expr: '' }],
          ['Tests H0: slope = 0 (no linear relationship).'],
          { code: ['B/S->T', 'N-2->D', `2*tcdf(abs(T),${INF},D)->A`], check: false }),
        cmp('slopeci', 'CI for slope', 'b +/- t* SE(b)', [v('B', 'slope b'), v('S', 'SE of b'), v('N', 'n'), v('C', 'confidence')],
          [{ sym: 'T', name: 't*', expr: '' }, { sym: 'E', name: 'margin', expr: '' }, { sym: 'L', name: 'lower', expr: '' }, { sym: 'U', name: 'upper', expr: '' }],
          ['Confidence interval for the true slope, df = n - 2.'],
          { code: ['invT(1-(1-C)/2,N-2)->T', 'T*S->E', 'B-E->L', 'B+E->U'], check: false }),
      ],
    },
    {
      id: 'which',
      menu: 'Which test?',
      notes: [
        'ONE categorical variable, 2 outcomes: 1-prop z (interval or test). Many outcomes: chi2 GOF.',
        'TWO categorical variables: chi2 test for independence (one sample) or homogeneity (several samples).',
        'ONE quantitative variable, one group: t interval / t test for a mean. Paired data: t on differences.',
        'ONE quantitative variable, two groups: 2-sample t. Two proportions: 2-prop z.',
        'TWO quantitative variables: regression, LinRegTTest for slope.',
        'Always: state parameter, check conditions, name the procedure, compute, conclude in context.',
        'p-value: probability of a result at least this extreme if H0 were true. Small p (< alpha) means evidence for Ha.',
        'Type I error: reject a true H0 (prob alpha). Type II: fail to reject a false H0. Power = 1 - P(Type II).',
      ],
      equations: [],
    },
  ],
};
